Ce répertoire méritait une application web dédiée
BastienDuplessier/angry_cuisine_nerd pull request #1
Opened 2021-07-21 23:22 UTC by xhtmlboi

Salut! Je me permet la rédaction en Français comme le contenu du dépôt est rédigé en Français (mais je peux, au besoin, éditer mon message). 
Comme dans le README, il est écrit que tu comptes faire murir ce dépôt en un véritable site web, j'ai décidé de faire une proposition qui ajoute la génération de pages statiques... dans un design assez sobre (mais je n'allais pas passer beaucoup de temps sur quelque chose que tu pouvais potentiellement refuser). 

Construire une version statique de ton dépôt m'a permis de rapidement trouver des pistes d'amélioration, donc si jamais tu refuses cette incroyable contribution, sache que je ne serai pas vexé.  Comme le code est généré dans le répertoire `_site`, le déploiement ne devrait pas être très compliqué.

A bientôt et n'hésite pas à me poser des questions si ça (le code et le fait d'avoir une page web) t'intéresse tout de même =) Impatient de lire les prochaines recettes!

2021-07-22 10:59 UTC, xhtmlboi commented
Comme @gr-im me l'a très peu cordialement fait remarqué, il faudrait que j'améliore un peu la validation des Metadonnées. Je pousse, quand le temps me le permet, une nouvelle version de YOCaml.

2021-08-01 13:24 UTC, xhtmlboi commented
L'API de YOCaml a pas mal changé (pour rendre le noyau du projet générique) donc voici un nouveau patch de mise à jour.

2021-08-01 13:30 UTC, gr-im commented on angry_cuisine_nerd.opam
> +  "yaml"
```diff
    "preface" {pinned}
    "yocaml" {pinned}
    "yocaml_unix" {pinned}
-   "yaml"
+  "yocaml_yaml" {pinned}
+  "yocaml_markdown" {pinned}
```

2021-08-01 13:35 UTC, gr-im commented on src/angry_generator.ml
> +          >>^ fun (x, _) -> x, get_recipe_url source)
Même si c'est de l'ordre du détail, j'aurais tendance à dire que cette ligne pourrait se reformuler en terme de Pair.Snd, Arrow.snd et Arrow. Mais je suppose que tu as choisi le plus lisible.
```

2021-08-01 13:36 UTC, gr-im commented on src/meta.ml
> +            <|> required_assoc text "quantity" step))
Je pense que c'est un peu pour la frime mais je ne suis pas sur que ça soit utile. A moins que @BastienDuplessier trouve que c'est une *killer-feature* de pouvoir choisir entre `qty` et `quantity`.

2021-08-01 13:37 UTC, gr-im commented on src/meta.ml
> +      obj
Cette fonction n'est plus utile.

2021-08-01 13:37 UTC, gr-im requested changes
Mis à part le fichier OPAM et la fonction inutile je pense que c'est bien fait. Merci pour la notification, c'est toujours agréable de voir "un usage concret".

2021-08-01 13:41 UTC, xhtmlboi commented on src/angry_generator.ml
> +          >>^ fun (x, _) -> x, get_recipe_url source)
Je ne trouve pas ça plus lisible, mais tu as raison. Pour le moment je le garde comme tel :)

2021-08-01 13:41 UTC, xhtmlboi commented on src/meta.ml
> +            <|> required_assoc text "quantity" step))
Oui, c'est clairement de la featurite :P

2021-08-01 13:53 UTC, xhtmlboi commented
J'ai pris en compte tes retours (et j'ai squashé tous les commits en 3 pour suivre proprement l'evolution de l'API).

2021-08-01 13:53 UTC, gr-im approved these changes

2021-08-02 14:30 UTC, xhtmlboi commented
Comme mentionné sur la PR originale (https://github.com/BastienDuplessier/angry_cuisine_nerd/pull/1)
les deux commits font la même chose mais en utilisant des approches différentes : 
- Template avec Mustache : https://github.com/BastienDuplessier/angry_cuisine_nerd/pull/1/commits/0c6dcfb04d44fb15f80ec74daf23a67d15e5d429
- Template avec Jingoo : https://github.com/BastienDuplessier/angry_cuisine_nerd/pull/1/commits/8a64bdeffdc47dbe815ca72103ebdd6ba0aab0db

@gr-im et moi préférons largement Jingoo :)

2021-08-12 07:54 UTC, merged

2021-08-12 07:57 UTC, BastienDuplessier commented
Merci beaucoup pour cette PR ! Ravi que ce repo ait servi pour améliorer YOCaml !
J'ai beaucoup appris en relisant le code avec xvw, pas sur que je sois capable de setup un autre blog tout seul mais avec un peu de copier coller je devrais m'en sortir :)